server:
  port: 8888
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://183.136.213.178/nginx
    username: eziep
    password: xxxxxxxx
    type: com.alibaba.druid.pool.DruidDataSource

nutz:
  dao:
    sqlmanager:
      paths:


page-store: 
  location: /data/temp/nginx/store